# Generated by Django 5.2.5 on 2025-08-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(max_length=20)),
                ("onu_sn", models.CharField(max_length=50)),
                ("plan_servicio", models.CharField(max_length=50)),
                ("fecha_alta", models.DateField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
