# Generated by Django 5.2.5 on 2025-08-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="fecha_desactivacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
